<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'ZipArchiveEx' => array($vendorDir . '/codeless/ziparchiveex/src'),
    'LogMore' => array($vendorDir . '/codeless/logmore/src'),
);
